name: Terraform EC2 Learning Lab

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  ec2-lab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Format check
        run: terraform fmt -check

      - name: Initialize Terraform
        run: terraform init

      - name: Validate configuration
        run: terraform validate

      - name: Show plan
        run: terraform plan -out=tfplan -input=false

      - name: Create EC2 instance
        run: terraform apply -auto-approve -input=false tfplan

      - name: Pause so you can view the EC2 instance
        run: sleep 120

      - name: Destroy EC2 instance
        run: terraform destroy -auto-approve -input=false
