name: AWS Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'AWS Deploy'
    runs-on: ubuntu-latest

    steps:
    # 1. Pull the repo code onto the runner
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Authenticate to AWS using secure repository keys
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Change to your preferred AWS region

    # 3. Setup the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # 4. Initialize the project (Downloads the AWS provider)
    - name: Terraform Init
      run: terraform init

    # 5. Build the infrastructure
    - name: Terraform Apply
      run: terraform apply -auto-approve
